<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="14" passed="9" failed="4" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-12-16T19:58:16 IST" name="Surefire suite" finished-at="2023-12-16T19:59:31 IST" duration-ms="74318">
    <groups>
    </groups>
    <test started-at="2023-12-16T19:58:16 IST" name="Surefire test" finished-at="2023-12-16T19:59:31 IST" duration-ms="74318">
      <class name="org.seleniumjavaautomation.junit.JunitTimeoutAndEcpectedExceptionTest">
        <test-method signature="exceptiontest2()" started-at="2023-12-16T19:58:17 IST" name="exceptiontest2" finished-at="2023-12-16T19:59:18 IST" duration-ms="61272" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- exceptiontest2 -->
        <test-method signature="testJunitTimeoutException() throws java.lang.Exception" started-at="2023-12-16T19:58:17 IST" name="testJunitTimeoutException" finished-at="2023-12-16T19:59:10 IST" duration-ms="53960" status="FAIL">
          <exception class="java.lang.Exception">
            <message>
              <![CDATA[test timed out after 2000 milliseconds]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Exception: test timed out after 2000 milliseconds
at java.base@17.0.6/java.lang.Thread.sleep(Native Method)
at app//org.seleniumjavaautomation.junit.JunitTimeoutAndEcpectedExceptionTest.testJunitTimeoutException(JunitTimeoutAndEcpectedExceptionTest.java:44)
at java.base@17.0.6/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base@17.0.6/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base@17.0.6/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base@17.0.6/java.lang.reflect.Method.invoke(Method.java:568)
at app//org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
at app//org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at app//org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
at app//org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at app//org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Exception -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testJunitTimeoutException -->
        <test-method signature="exceptiontest1()" started-at="2023-12-16T19:58:17 IST" name="exceptiontest1" finished-at="2023-12-16T19:59:14 IST" duration-ms="57570" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at org.seleniumjavaautomation.junit.JunitTimeoutAndEcpectedExceptionTest.exceptiontest1(JunitTimeoutAndEcpectedExceptionTest.java:52)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
at org.junit.runners.Suite.runChild(Suite.java:127)
at org.junit.runners.Suite.runChild(Suite.java:26)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
at org.testng.junit.JUnit4TestRunner.start(JUnit4TestRunner.java:78)
at org.testng.junit.JUnit4TestRunner.run(JUnit4TestRunner.java:63)
at org.testng.TestRunner$1.run(TestRunner.java:710)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.runJUnitWorkers(TestRunner.java:927)
at org.testng.TestRunner.privateRunJUnit(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:198)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- exceptiontest1 -->
        <test-method signature="exceptiontest2()" started-at="2023-12-16T19:59:18 IST" name="exceptiontest2" finished-at="2023-12-16T19:59:31 IST" duration-ms="12826" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- exceptiontest2 -->
        <test-method signature="exceptiontest1()" started-at="2023-12-16T19:59:18 IST" name="exceptiontest1" finished-at="2023-12-16T19:59:27 IST" duration-ms="9130" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at org.seleniumjavaautomation.junit.JunitTimeoutAndEcpectedExceptionTest.exceptiontest1(JunitTimeoutAndEcpectedExceptionTest.java:52)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
at org.testng.junit.JUnit4TestRunner.start(JUnit4TestRunner.java:78)
at org.testng.junit.JUnit4TestRunner.run(JUnit4TestRunner.java:63)
at org.testng.TestRunner$1.run(TestRunner.java:710)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.runJUnitWorkers(TestRunner.java:927)
at org.testng.TestRunner.privateRunJUnit(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:198)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- exceptiontest1 -->
        <test-method signature="testJunitTimeoutException() throws java.lang.Exception" started-at="2023-12-16T19:59:18 IST" name="testJunitTimeoutException" finished-at="2023-12-16T19:59:23 IST" duration-ms="5583" status="FAIL">
          <exception class="java.lang.Exception">
            <message>
              <![CDATA[test timed out after 2000 milliseconds]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Exception: test timed out after 2000 milliseconds
at java.base@17.0.6/java.lang.Thread.sleep(Native Method)
at app//org.seleniumjavaautomation.junit.JunitTimeoutAndEcpectedExceptionTest.testJunitTimeoutException(JunitTimeoutAndEcpectedExceptionTest.java:44)
at java.base@17.0.6/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base@17.0.6/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base@17.0.6/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base@17.0.6/java.lang.reflect.Method.invoke(Method.java:568)
at app//org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
at app//org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at app//org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
at app//org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at app//org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Exception -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testJunitTimeoutException -->
      </class> <!-- org.seleniumjavaautomation.junit.JunitTimeoutAndEcpectedExceptionTest -->
      <class name="org.seleniumjavaautomation.junit.JunitBCAC">
        <test-method signature="testMethod1() throws java.lang.Exception" started-at="2023-12-16T19:58:17 IST" name="testMethod1" finished-at="2023-12-16T19:59:02 IST" duration-ms="45552" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMethod1 -->
        <test-method signature="testMethod3()" started-at="2023-12-16T19:58:17 IST" name="testMethod3" finished-at="2023-12-16T19:59:04 IST" duration-ms="47886" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMethod3 -->
        <test-method signature="testMethod2() throws java.lang.InterruptedException" started-at="2023-12-16T19:58:17 IST" name="testMethod2" finished-at="2023-12-16T19:59:04 IST" duration-ms="47730" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMethod2 -->
      </class> <!-- org.seleniumjavaautomation.junit.JunitBCAC -->
      <class name="org.seleniumjavaautomation.junit.Junittest2">
        <test-method signature="testMethod1() throws java.lang.Exception" started-at="2023-12-16T19:58:17 IST" name="testMethod1" finished-at="2023-12-16T19:58:39 IST" duration-ms="22794" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMethod1 -->
        <test-method signature="testMethod2() throws java.lang.InterruptedException" started-at="2023-12-16T19:58:17 IST" name="testMethod2" finished-at="2023-12-16T19:58:48 IST" duration-ms="31983" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMethod2 -->
        <test-method signature="testMethod3()" started-at="2023-12-16T19:58:17 IST" name="testMethod3" finished-at="2023-12-16T19:58:54 IST" duration-ms="37755" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMethod3 -->
        <test-method signature="testMethod4() throws java.lang.InterruptedException" started-at="2023-12-16T19:58:17 IST" name="testMethod4" finished-at="2023-12-16T19:58:17 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMethod4 -->
      </class> <!-- org.seleniumjavaautomation.junit.Junittest2 -->
      <class name="org.seleniumjavaautomation.junit.Junittest1">
        <test-method signature="testMethodClass1() throws java.lang.Exception" started-at="2023-12-16T19:58:17 IST" name="testMethodClass1" finished-at="2023-12-16T19:58:29 IST" duration-ms="12747" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMethodClass1 -->
      </class> <!-- org.seleniumjavaautomation.junit.Junittest1 -->
    </test> <!-- Surefire test -->
  </suite> <!-- Surefire suite -->
</testng-results>
